// Exact loader, compiler/toolchain, wrapper, script-shell, editor, pager, and delegated-executor
// selectors. Go, GCC, and Rust variables are included whenever they can redirect a subprocess or
// load executable configuration that selects one.
const FORBIDDEN_ENVIRONMENT_NAMES = new Set([
  "BASH_ENV",
  "CDPATH",
  "DYLD_FRAMEWORK_PATH",
  "DYLD_INSERT_LIBRARIES",
  "DYLD_LIBRARY_PATH",
  "ENV",
  "GIT_CONFIG_PARAMETERS",
  "GIT_CONFIG_SYSTEM",
  "GIT_CONFIG_GLOBAL",
  "GIT_SSH_COMMAND",
  "GIT_SSH",
  "GIT_ASKPASS",
  "SSH_ASKPASS",
  "GIT_EXEC_PATH",
  "GIT_CONFIG_COUNT",
  "GIT_PAGER",
  "PAGER",
  "GIT_EDITOR",
  "GIT_SEQUENCE_EDITOR",
  "GIT_EXTERNAL_DIFF",
  "GIT_PROXY_COMMAND",
  "VISUAL",
  "EDITOR",
  "LESSOPEN",
  "LESSCLOSE",
  "RUSTC",
  "RUSTC_WRAPPER",
  "RUSTC_WORKSPACE_WRAPPER",
  "RUSTDOC",
  "RUSTDOC_WRAPPER",
  "RUSTFLAGS",
  "RUSTDOCFLAGS",
  "CARGO_BUILD_RUSTC",
  "CARGO_BUILD_RUSTC_WRAPPER",
  "CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER",
  "CARGO_BUILD_RUSTDOC",
  "CARGO_BUILD_RUSTDOC_WRAPPER",
  "CARGO_ENCODED_RUSTFLAGS",
  "CARGO_ENCODED_RUSTDOCFLAGS",
  "CARGO_HOME",
  "GOROOT",
  "GOTOOLDIR",
  "GOTOOLCHAIN",
  "GOCACHEPROG",
  "GOAUTH",
  "GOENV",
  "GOFLAGS",
  "GCCGO",
  "GCC_EXEC_PREFIX",
  "COMPILER_PATH",
  "AR",
  "AS",
  "LD",
  "NM",
  "OBJCOPY",
  "OBJDUMP",
  "RANLIB",
  "STRIP",
  "PKG_CONFIG",
  "NPM_CONFIG_SCRIPT_SHELL",
  "npm_config_script_shell",
  "NPM_CONFIG_NODE_GYP",
  "npm_config_node_gyp",
  "BUNDLE_GEMFILE",
  "YARN_PATH",
  "SHELL",
  "COMSPEC",
  "MANPAGER",
  "SYSTEMD_PAGER",
  "SYSTEMD_EDITOR",
  "HGEDITOR",
  "SVN_EDITOR",
  "CC",
  "CXX",
  "NODE_OPTIONS",
  "NODE_PATH",
  "JAVA_TOOL_OPTIONS",
  "JDK_JAVA_OPTIONS",
  "_JAVA_OPTIONS",
  "PERL5OPT",
  "PERL5LIB",
  "PS4",
  "PROMPT_COMMAND",
  "PYTHONHOME",
  "PYTHONPATH",
  "PYTHONSTARTUP",
  "LUA_INIT",
  "PHPRC",
  "PHP_INI_SCAN_DIR",
  "RUBYOPT",
  "RUBYLIB",
  "SHELLOPTS",
  "ZDOTDIR"
]);

// Families whose suffixes are attacker-selected configuration slots or dynamic loader controls.
const FORBIDDEN_ENVIRONMENT_PREFIXES = Object.freeze([
  "DYLD_",
  "LD_",
  "LUA_INIT_",
  "GIT_CONFIG_KEY_",
  "GIT_CONFIG_VALUE_"
]);

export const isForbiddenEnvironmentName = (name: string): boolean =>
  FORBIDDEN_ENVIRONMENT_NAMES.has(name) ||
  FORBIDDEN_ENVIRONMENT_PREFIXES.some((prefix) => name.startsWith(prefix)) ||
  /^CARGO_TARGET_[A-Z0-9_]+_(?:LINKER|RUNNER|RUSTFLAGS)$/.test(name) ||
  name === "ELECTRON_RUN_AS_NODE";
