import type { RunStatus, StoredDomainEvent } from "@autostack/contracts";

import { createDashboardEventStream } from "./dashboard-fixture-support.js";
import {
  seedDashboardApprovals,
  seedDashboardClarification,
  seedDashboardCommands,
  seedDashboardUsageEvents
} from "./dashboard-fixture-detail-events.js";
import { seedDashboardRuns, seedDashboardWorkItems } from "./dashboard-fixture-entities.js";
import {
  RUN_ACTIVE_IMPLEMENTING,
  RUN_ACTIVE_REVIEWING,
  RUN_AWAITING_PLAN_APPROVAL,
  RUN_COMPLETED_FAST,
  RUN_COMPLETED_SLOW,
  RUN_FAILED,
  RUN_NEEDS_CLARIFICATION,
  WORKSPACE_ID
} from "./dashboard-fixture-ids.js";
import { seedDashboardStages } from "./dashboard-fixture-stages.js";

export { DASHBOARD_RUN_IDS } from "./dashboard-fixture-ids.js";

/**
 * The seeded control-room dashboard fixture (Task 9a, step 1). Every event this composes is a
 * literal, hand-written value — this module (and the `dashboard-fixture-*.ts` files it composes)
 * is testing support for `deriveFactoryMetrics`, never generated by it. IDs are minted through the
 * existing deterministic factory (never `crypto.randomUUID()`) only because `StoredDomainEvent`
 * identifiers are branded types the schema alone can produce; the narrative — which run does what,
 * in what order, at which literal timestamp — is authored by hand across the composed files.
 *
 * Composition (binding, `docs/superpowers/plans/2026-08-26-autostack-s6-workbench.md` Task 9a):
 * 7 work items (3 github, 2 slack, 1 manual, 1 api); 7 runs landing 2 active, 1 waiting on
 * approval, 1 blocked on clarification, 1 failed, 2 completed; 19 stage lease/succeed/fail triples
 * across all six stages including one `implement` at `attempt: 3`; 4 approvals, 3 decided with
 * known request -> decide gaps; 5 `command.completed`; 1 `publish` stage success. Plus (D4 revised)
 * `agent.session_event` usage events covering a fully-reported run, a run with unknown members, and
 * a reported `0` (the falsy-zero trap).
 */
const stream = createDashboardEventStream(WORKSPACE_ID);

seedDashboardWorkItems(stream);
seedDashboardRuns(stream);
seedDashboardStages(stream);
seedDashboardApprovals(stream);
seedDashboardCommands(stream);
seedDashboardUsageEvents(stream);
seedDashboardClarification(stream);

export const SEEDED_DASHBOARD_EVENTS: readonly StoredDomainEvent[] = stream.events;

/**
 * The fixture's advertised composition, hand-computed alongside the seeding calls above. The
 * fixture-integrity test re-derives every one of these numbers from `SEEDED_DASHBOARD_EVENTS`
 * itself, so a later edit to the seeding files that silently changes the arithmetic fails there,
 * next to the seeder, rather than in the derivation test.
 */
export const DASHBOARD_FIXTURE_COMPOSITION = {
  eventTypeCounts: {
    "work_item.created": 7,
    "run.created": 7,
    "run.transitioned": 15,
    "stage.queued": 19,
    "stage.leased": 19,
    "stage.succeeded": 18,
    "stage.failed": 1,
    "approval.requested": 4,
    "approval.decided": 3,
    "command.completed": 5,
    "agent.session_event": 3,
    "clarification.requested": 1
  },
  totalEventCount: 102,
  workItemSourceCounts: { github: 3, slack: 2, manual: 1, api: 1 },
  runFinalStatuses: {
    [RUN_COMPLETED_FAST]: "completed",
    [RUN_COMPLETED_SLOW]: "completed",
    [RUN_FAILED]: "failed",
    [RUN_ACTIVE_IMPLEMENTING]: "implementing",
    [RUN_ACTIVE_REVIEWING]: "reviewing",
    [RUN_AWAITING_PLAN_APPROVAL]: "awaiting_plan_approval",
    [RUN_NEEDS_CLARIFICATION]: "needs_clarification"
  } satisfies Readonly<Record<string, RunStatus>>,
  // 240s and 600s, the plan's own cycle-time example: median = (240_000 + 600_000) / 2 = 420_000 ms.
  cycleTimesMs: { completedFast: 240_000, completedSlow: 600_000 },
  // sorted [30_000, 60_000, 120_000] -> median (odd count, middle value) = 60_000 ms.
  approvalWaitsMs: { publishFast: 30_000, planFast: 60_000, permissionReviewing: 120_000 },
  implementRetryAttempt: { runId: RUN_FAILED, maxAttempt: 3 },
  usageTotals: {
    tokens: {
      input: { reportedSum: 1_800, unknownCount: 0 },
      output: { reportedSum: 700, unknownCount: 1 },
      cachedInput: { reportedSum: 100, unknownCount: 1 },
      reasoning: { reportedSum: 50, unknownCount: 0 }
    },
    cost: { reportedMicros: 300_000, unknownCount: 1 }
  }
} as const;
